package com.sinapsistech.laboratorio.model;

// Generated Mar 2, 2015 7:12:28 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Componente generated by hbm2java
 */
@Entity
@Table(name = "componente"
      , schema = "public")
public class Componente implements java.io.Serializable
{

   private int idComponente;
   private String nombre;
   private String flagEstado;
   private Date fechaReg;
   private String usuarioReg;
   private Date fechaMod;
   private String usuarioMod;
   private Date fechaBorrado;
   private String usuarioBorrado;
   private Boolean flagAgrupacion;
   private Set<ExamenComponente> examenComponentes = new HashSet<ExamenComponente>(0);

   public Componente()
   {
   }

   public Componente(int idComponente, String nombre)
   {
      this.idComponente = idComponente;
      this.nombre = nombre;
   }

   public Componente(int idComponente, String nombre, String flagEstado, Date fechaReg, String usuarioReg, Date fechaMod, String usuarioMod, Date fechaBorrado, String usuarioBorrado, Boolean flagAgrupacion, Set<ExamenComponente> examenComponentes)
   {
      this.idComponente = idComponente;
      this.nombre = nombre;
      this.flagEstado = flagEstado;
      this.fechaReg = fechaReg;
      this.usuarioReg = usuarioReg;
      this.fechaMod = fechaMod;
      this.usuarioMod = usuarioMod;
      this.fechaBorrado = fechaBorrado;
      this.usuarioBorrado = usuarioBorrado;
      this.flagAgrupacion = flagAgrupacion;
      this.examenComponentes = examenComponentes;
   }

   @Id
   @GeneratedValue(strategy=GenerationType.IDENTITY)
   @Column(name = "id_componente", unique = true, nullable = false, insertable=false)
   public int getIdComponente()
   {
      return this.idComponente;
   }

   public void setIdComponente(int idComponente)
   {
      this.idComponente = idComponente;
   }

   @Column(name = "nombre", nullable = false, length = 50)
   public String getNombre()
   {
      return this.nombre;
   }

   public void setNombre(String nombre)
   {
      this.nombre = nombre;
   }

   @Column(name = "flag_estado", length = 2)
   public String getFlagEstado()
   {
      return this.flagEstado;
   }

   public void setFlagEstado(String flagEstado)
   {
      this.flagEstado = flagEstado;
   }

   @Temporal(TemporalType.TIMESTAMP)
   @Column(name = "fecha_reg", length = 29)
   public Date getFechaReg()
   {
      return this.fechaReg;
   }

   public void setFechaReg(Date fechaReg)
   {
      this.fechaReg = fechaReg;
   }

   @Column(name = "usuario_reg", length = 30)
   public String getUsuarioReg()
   {
      return this.usuarioReg;
   }

   public void setUsuarioReg(String usuarioReg)
   {
      this.usuarioReg = usuarioReg;
   }

   @Temporal(TemporalType.TIMESTAMP)
   @Column(name = "fecha_mod", length = 29)
   public Date getFechaMod()
   {
      return this.fechaMod;
   }

   public void setFechaMod(Date fechaMod)
   {
      this.fechaMod = fechaMod;
   }

   @Column(name = "usuario_mod", length = 30)
   public String getUsuarioMod()
   {
      return this.usuarioMod;
   }

   public void setUsuarioMod(String usuarioMod)
   {
      this.usuarioMod = usuarioMod;
   }

   @Temporal(TemporalType.TIMESTAMP)
   @Column(name = "fecha_borrado", length = 29)
   public Date getFechaBorrado()
   {
      return this.fechaBorrado;
   }

   public void setFechaBorrado(Date fechaBorrado)
   {
      this.fechaBorrado = fechaBorrado;
   }

   @Column(name = "usuario_borrado", length = 30)
   public String getUsuarioBorrado()
   {
      return this.usuarioBorrado;
   }

   public void setUsuarioBorrado(String usuarioBorrado)
   {
      this.usuarioBorrado = usuarioBorrado;
   }

   @Column(name = "flag_agrupacion")
   public Boolean getFlagAgrupacion()
   {
      return this.flagAgrupacion;
   }

   public void setFlagAgrupacion(Boolean flagAgrupacion)
   {
      this.flagAgrupacion = flagAgrupacion;
   }

   @OneToMany(fetch = FetchType.LAZY, mappedBy = "componente")
   public Set<ExamenComponente> getExamenComponentes()
   {
      return this.examenComponentes;
   }

   public void setExamenComponentes(Set<ExamenComponente> examenComponentes)
   {
      this.examenComponentes = examenComponentes;
   }

}
