package com.sinapsistech.laboratorio.model;

// Generated Mar 2, 2015 7:12:28 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Compania generated by hbm2java
 */
@Entity
@Table(name = "compania"
      , schema = "public")
public class Compania implements java.io.Serializable
{

   private int idCia;
   private String nombreCorto;
   private String nombreLargo;
   private Date fechaInicioOperaciones;
   private String flagEstado;
   private Date fechaReg;
   private String usuarioReg;
   private String logo;
   private Date fechaFinOperaciones;
   private String nombreResponsable;
   private String telefonoResponsable;
   private String direccionLegal;
   private String emailResponsable;
   private Set<Usuario> usuarios = new HashSet<Usuario>(0);

   public Compania()
   {
   }

   public Compania(int idCia, String nombreCorto, String nombreLargo)
   {
      this.idCia = idCia;
      this.nombreCorto = nombreCorto;
      this.nombreLargo = nombreLargo;
   }

   public Compania(int idCia, String nombreCorto, String nombreLargo, Date fechaInicioOperaciones, String flagEstado, Date fechaReg, String usuarioReg, String logo, Date fechaFinOperaciones, String nombreResponsable, String telefonoResponsable, String direccionLegal, String emailResponsable, Set<Usuario> usuarios)
   {
      this.idCia = idCia;
      this.nombreCorto = nombreCorto;
      this.nombreLargo = nombreLargo;
      this.fechaInicioOperaciones = fechaInicioOperaciones;
      this.flagEstado = flagEstado;
      this.fechaReg = fechaReg;
      this.usuarioReg = usuarioReg;
      this.logo = logo;
      this.fechaFinOperaciones = fechaFinOperaciones;
      this.nombreResponsable = nombreResponsable;
      this.telefonoResponsable = telefonoResponsable;
      this.direccionLegal = direccionLegal;
      this.emailResponsable = emailResponsable;
      this.usuarios = usuarios;
   }

   @Id
   @GeneratedValue(strategy=GenerationType.IDENTITY)
   @Column(name = "id_cia", unique = true, nullable = false, insertable=false)
   public int getIdCia()
   {
      return this.idCia;
   }

   public void setIdCia(int idCia)
   {
      this.idCia = idCia;
   }

   @Column(name = "nombre_corto", nullable = false, length = 20)
   public String getNombreCorto()
   {
      return this.nombreCorto;
   }

   public void setNombreCorto(String nombreCorto)
   {
      this.nombreCorto = nombreCorto;
   }

   @Column(name = "nombre_largo", nullable = false, length = 200)
   public String getNombreLargo()
   {
      return this.nombreLargo;
   }

   public void setNombreLargo(String nombreLargo)
   {
      this.nombreLargo = nombreLargo;
   }

   @Temporal(TemporalType.TIMESTAMP)
   @Column(name = "fecha_inicio_operaciones", length = 29)
   public Date getFechaInicioOperaciones()
   {
      return this.fechaInicioOperaciones;
   }

   public void setFechaInicioOperaciones(Date fechaInicioOperaciones)
   {
      this.fechaInicioOperaciones = fechaInicioOperaciones;
   }

   @Column(name = "flag_estado", length = 2)
   public String getFlagEstado()
   {
      return this.flagEstado;
   }

   public void setFlagEstado(String flagEstado)
   {
      this.flagEstado = flagEstado;
   }

   @Temporal(TemporalType.TIMESTAMP)
   @Column(name = "fecha_reg", length = 29)
   public Date getFechaReg()
   {
      return this.fechaReg;
   }

   public void setFechaReg(Date fechaReg)
   {
      this.fechaReg = fechaReg;
   }

   @Column(name = "usuario_reg", length = 30)
   public String getUsuarioReg()
   {
      return this.usuarioReg;
   }

   public void setUsuarioReg(String usuarioReg)
   {
      this.usuarioReg = usuarioReg;
   }

   @Column(name = "logo", length = 100)
   public String getLogo()
   {
      return this.logo;
   }

   public void setLogo(String logo)
   {
      this.logo = logo;
   }

   @Temporal(TemporalType.TIMESTAMP)
   @Column(name = "fecha_fin_operaciones", length = 29)
   public Date getFechaFinOperaciones()
   {
      return this.fechaFinOperaciones;
   }

   public void setFechaFinOperaciones(Date fechaFinOperaciones)
   {
      this.fechaFinOperaciones = fechaFinOperaciones;
   }

   @Column(name = "nombre_responsable", length = 100)
   public String getNombreResponsable()
   {
      return this.nombreResponsable;
   }

   public void setNombreResponsable(String nombreResponsable)
   {
      this.nombreResponsable = nombreResponsable;
   }

   @Column(name = "telefono_responsable", length = 30)
   public String getTelefonoResponsable()
   {
      return this.telefonoResponsable;
   }

   public void setTelefonoResponsable(String telefonoResponsable)
   {
      this.telefonoResponsable = telefonoResponsable;
   }

   @Column(name = "direccion_legal", length = 200)
   public String getDireccionLegal()
   {
      return this.direccionLegal;
   }

   public void setDireccionLegal(String direccionLegal)
   {
      this.direccionLegal = direccionLegal;
   }

   @Column(name = "email_responsable", length = 100)
   public String getEmailResponsable()
   {
      return this.emailResponsable;
   }

   public void setEmailResponsable(String emailResponsable)
   {
      this.emailResponsable = emailResponsable;
   }

   @OneToMany(fetch = FetchType.LAZY, mappedBy = "compania")
   public Set<Usuario> getUsuarios()
   {
      return this.usuarios;
   }

   public void setUsuarios(Set<Usuario> usuarios)
   {
      this.usuarios = usuarios;
   }

}
