package com.sinapsistech.laboratorio.model;

// Generated Mar 2, 2015 7:12:28 PM by Hibernate Tools 4.3.1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Entrega generated by hbm2java
 */
@Entity
@Table(name = "entrega"
      , schema = "public")
public class Entrega implements java.io.Serializable
{

   private int idEntrega;
   private SolicitudDetalle solicitudDetalle;
   private Trabajador trabajador;
   private String observaciones;
   private Date fechaEntrega;
   private String nombreCompleto;
   private Integer documentoIdentidad;
   private String telefono;
   private String flagEstado;
   private String usuarioReg;
   private Date fechaMod;
   private String usuarioMod;
   private Date fechaBorrado;
   private String usuarioBorrado;

   public Entrega()
   {
   }

   public Entrega(int idEntrega, SolicitudDetalle solicitudDetalle, Trabajador trabajador, String nombreCompleto)
   {
      this.idEntrega = idEntrega;
      this.solicitudDetalle = solicitudDetalle;
      this.trabajador = trabajador;
      this.nombreCompleto = nombreCompleto;
   }

   public Entrega(int idEntrega, SolicitudDetalle solicitudDetalle, Trabajador trabajador, String observaciones, Date fechaEntrega, String nombreCompleto, Integer documentoIdentidad, String telefono, String flagEstado, String usuarioReg, Date fechaMod, String usuarioMod, Date fechaBorrado, String usuarioBorrado)
   {
      this.idEntrega = idEntrega;
      this.solicitudDetalle = solicitudDetalle;
      this.trabajador = trabajador;
      this.observaciones = observaciones;
      this.fechaEntrega = fechaEntrega;
      this.nombreCompleto = nombreCompleto;
      this.documentoIdentidad = documentoIdentidad;
      this.telefono = telefono;
      this.flagEstado = flagEstado;
      this.usuarioReg = usuarioReg;
      this.fechaMod = fechaMod;
      this.usuarioMod = usuarioMod;
      this.fechaBorrado = fechaBorrado;
      this.usuarioBorrado = usuarioBorrado;
   }

   @Id
   @GeneratedValue(strategy=GenerationType.IDENTITY)
   @Column(name = "id_entrega", unique = true, nullable = false, insertable=false)
   public int getIdEntrega()
   {
      return this.idEntrega;
   }

   public void setIdEntrega(int idEntrega)
   {
      this.idEntrega = idEntrega;
   }

   @ManyToOne(fetch = FetchType.LAZY)
   @JoinColumn(name = "id_solicitud_detalle", nullable = false)
   public SolicitudDetalle getSolicitudDetalle()
   {
      return this.solicitudDetalle;
   }

   public void setSolicitudDetalle(SolicitudDetalle solicitudDetalle)
   {
      this.solicitudDetalle = solicitudDetalle;
   }

   @ManyToOne(fetch = FetchType.LAZY)
   @JoinColumn(name = "id_trabajador", nullable = false)
   public Trabajador getTrabajador()
   {
      return this.trabajador;
   }

   public void setTrabajador(Trabajador trabajador)
   {
      this.trabajador = trabajador;
   }

   @Column(name = "observaciones", length = 200)
   public String getObservaciones()
   {
      return this.observaciones;
   }

   public void setObservaciones(String observaciones)
   {
      this.observaciones = observaciones;
   }

   @Temporal(TemporalType.TIMESTAMP)
   @Column(name = "fecha_entrega", length = 29)
   public Date getFechaEntrega()
   {
      return this.fechaEntrega;
   }

   public void setFechaEntrega(Date fechaEntrega)
   {
      this.fechaEntrega = fechaEntrega;
   }

   @Column(name = "nombre_completo", nullable = false, length = 100)
   public String getNombreCompleto()
   {
      return this.nombreCompleto;
   }

   public void setNombreCompleto(String nombreCompleto)
   {
      this.nombreCompleto = nombreCompleto;
   }

   @Column(name = "documento_identidad")
   public Integer getDocumentoIdentidad()
   {
      return this.documentoIdentidad;
   }

   public void setDocumentoIdentidad(Integer documentoIdentidad)
   {
      this.documentoIdentidad = documentoIdentidad;
   }

   @Column(name = "telefono", length = 20)
   public String getTelefono()
   {
      return this.telefono;
   }

   public void setTelefono(String telefono)
   {
      this.telefono = telefono;
   }

   @Column(name = "flag_estado", length = 2)
   public String getFlagEstado()
   {
      return this.flagEstado;
   }

   public void setFlagEstado(String flagEstado)
   {
      this.flagEstado = flagEstado;
   }

   @Column(name = "usuario_reg", length = 30)
   public String getUsuarioReg()
   {
      return this.usuarioReg;
   }

   public void setUsuarioReg(String usuarioReg)
   {
      this.usuarioReg = usuarioReg;
   }

   @Temporal(TemporalType.TIMESTAMP)
   @Column(name = "fecha_mod", length = 29)
   public Date getFechaMod()
   {
      return this.fechaMod;
   }

   public void setFechaMod(Date fechaMod)
   {
      this.fechaMod = fechaMod;
   }

   @Column(name = "usuario_mod", length = 30)
   public String getUsuarioMod()
   {
      return this.usuarioMod;
   }

   public void setUsuarioMod(String usuarioMod)
   {
      this.usuarioMod = usuarioMod;
   }

   @Temporal(TemporalType.TIMESTAMP)
   @Column(name = "fecha_borrado", length = 29)
   public Date getFechaBorrado()
   {
      return this.fechaBorrado;
   }

   public void setFechaBorrado(Date fechaBorrado)
   {
      this.fechaBorrado = fechaBorrado;
   }

   @Column(name = "usuario_borrado", length = 30)
   public String getUsuarioBorrado()
   {
      return this.usuarioBorrado;
   }

   public void setUsuarioBorrado(String usuarioBorrado)
   {
      this.usuarioBorrado = usuarioBorrado;
   }

}
