package com.sinapsistech.laboratorio.model;

// Generated Mar 2, 2015 7:12:28 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ListaPrecio generated by hbm2java
 */
@Entity
@Table(name = "lista_precio"
      , schema = "public")
public class ListaPrecio implements java.io.Serializable
{

   private int idListaPrecio;
   private Examen examen;
   private TipoTarifa tipoTarifa;
   private Date fechaInicio;
   private Date fechaFin;
   private Double precioLista;
   private String decripcion;
   private String flagEstado;
   private Date fechaReg;
   private String usuarioReg;
   private Date fechaMod;
   private String usuarioMod;
   private Date fechaBorrado;
   private String usuarioBorrado;
   private Set<SolicitudDetalle> solicitudDetalles = new HashSet<SolicitudDetalle>(0);

   public ListaPrecio()
   {
   }

   public ListaPrecio(int idListaPrecio, Examen examen, TipoTarifa tipoTarifa, Date fechaInicio, Date fechaFin, String decripcion)
   {
      this.idListaPrecio = idListaPrecio;
      this.examen = examen;
      this.tipoTarifa = tipoTarifa;
      this.fechaInicio = fechaInicio;
      this.fechaFin = fechaFin;
      this.decripcion = decripcion;
   }

   public ListaPrecio(int idListaPrecio, Examen examen, TipoTarifa tipoTarifa, Date fechaInicio, Date fechaFin, Double precioLista, String decripcion, String flagEstado, Date fechaReg, String usuarioReg, Date fechaMod, String usuarioMod, Date fechaBorrado, String usuarioBorrado, Set<SolicitudDetalle> solicitudDetalles)
   {
      this.idListaPrecio = idListaPrecio;
      this.examen = examen;
      this.tipoTarifa = tipoTarifa;
      this.fechaInicio = fechaInicio;
      this.fechaFin = fechaFin;
      this.precioLista = precioLista;
      this.decripcion = decripcion;
      this.flagEstado = flagEstado;
      this.fechaReg = fechaReg;
      this.usuarioReg = usuarioReg;
      this.fechaMod = fechaMod;
      this.usuarioMod = usuarioMod;
      this.fechaBorrado = fechaBorrado;
      this.usuarioBorrado = usuarioBorrado;
      this.solicitudDetalles = solicitudDetalles;
   }

   @Id
   @GeneratedValue(strategy=GenerationType.IDENTITY)
   @Column(name = "id_lista_precio", unique = true, nullable = false, insertable=false)
   public int getIdListaPrecio()
   {
      return this.idListaPrecio;
   }

   public void setIdListaPrecio(int idListaPrecio)
   {
      this.idListaPrecio = idListaPrecio;
   }

   @ManyToOne(fetch = FetchType.LAZY)
   @JoinColumn(name = "id_examen", nullable = false)
   public Examen getExamen()
   {
      return this.examen;
   }

   public void setExamen(Examen examen)
   {
      this.examen = examen;
   }

   @ManyToOne(fetch = FetchType.LAZY)
   @JoinColumn(name = "id_tipo_tarifa", nullable = false)
   public TipoTarifa getTipoTarifa()
   {
      return this.tipoTarifa;
   }

   public void setTipoTarifa(TipoTarifa tipoTarifa)
   {
      this.tipoTarifa = tipoTarifa;
   }

   @Temporal(TemporalType.TIMESTAMP)
   @Column(name = "fecha_inicio", nullable = false, length = 29)
   public Date getFechaInicio()
   {
      return this.fechaInicio;
   }

   public void setFechaInicio(Date fechaInicio)
   {
      this.fechaInicio = fechaInicio;
   }

   @Temporal(TemporalType.TIMESTAMP)
   @Column(name = "fecha_fin", nullable = false, length = 29)
   public Date getFechaFin()
   {
      return this.fechaFin;
   }

   public void setFechaFin(Date fechaFin)
   {
      this.fechaFin = fechaFin;
   }

   @Column(name = "precio_lista", precision = 17, scale = 17)
   public Double getPrecioLista()
   {
      return this.precioLista;
   }

   public void setPrecioLista(Double precioLista)
   {
      this.precioLista = precioLista;
   }

   @Column(name = "decripcion", nullable = false, length = 200)
   public String getDecripcion()
   {
      return this.decripcion;
   }

   public void setDecripcion(String decripcion)
   {
      this.decripcion = decripcion;
   }

   @Column(name = "flag_estado", length = 2)
   public String getFlagEstado()
   {
      return this.flagEstado;
   }

   public void setFlagEstado(String flagEstado)
   {
      this.flagEstado = flagEstado;
   }

   @Temporal(TemporalType.TIMESTAMP)
   @Column(name = "fecha_reg", length = 29)
   public Date getFechaReg()
   {
      return this.fechaReg;
   }

   public void setFechaReg(Date fechaReg)
   {
      this.fechaReg = fechaReg;
   }

   @Column(name = "usuario_reg", length = 30)
   public String getUsuarioReg()
   {
      return this.usuarioReg;
   }

   public void setUsuarioReg(String usuarioReg)
   {
      this.usuarioReg = usuarioReg;
   }

   @Temporal(TemporalType.TIMESTAMP)
   @Column(name = "fecha_mod", length = 29)
   public Date getFechaMod()
   {
      return this.fechaMod;
   }

   public void setFechaMod(Date fechaMod)
   {
      this.fechaMod = fechaMod;
   }

   @Column(name = "usuario_mod", length = 30)
   public String getUsuarioMod()
   {
      return this.usuarioMod;
   }

   public void setUsuarioMod(String usuarioMod)
   {
      this.usuarioMod = usuarioMod;
   }

   @Temporal(TemporalType.TIMESTAMP)
   @Column(name = "fecha_borrado", length = 29)
   public Date getFechaBorrado()
   {
      return this.fechaBorrado;
   }

   public void setFechaBorrado(Date fechaBorrado)
   {
      this.fechaBorrado = fechaBorrado;
   }

   @Column(name = "usuario_borrado", length = 30)
   public String getUsuarioBorrado()
   {
      return this.usuarioBorrado;
   }

   public void setUsuarioBorrado(String usuarioBorrado)
   {
      this.usuarioBorrado = usuarioBorrado;
   }

   @OneToMany(fetch = FetchType.LAZY, mappedBy = "listaPrecio")
   public Set<SolicitudDetalle> getSolicitudDetalles()
   {
      return this.solicitudDetalles;
   }

   public void setSolicitudDetalles(Set<SolicitudDetalle> solicitudDetalles)
   {
      this.solicitudDetalles = solicitudDetalles;
   }

}
