package com.sinapsistech.laboratorio.model;

// Generated Mar 2, 2015 7:12:28 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Persona generated by hbm2java
 */
@Entity
@Table(name = "persona"
      , schema = "public")
public class Persona implements java.io.Serializable
{

   private int idPersona;
   private Ciudad ciudad;
   private ClasePaciente clasePaciente;
   private TipoPersona tipoPersona;
   private String nombre;
   private String apellidoPaterno;
   private String apellidoMaterno;
   private int documentoIdentidad;
   private int telefono1;
   private int telefono2;
   private String sexo;
   private String email;
   private Date fechaNacimiento;
   private String grupoSanguineo;
   private Date fechaReg;
   private String usuarioReg;
   private Date fechaMod;
   private String usuarioMod;
   private Date fechaBorrado;
   private String usuarioBorrado;
   private Set<Trabajador> trabajadors = new HashSet<Trabajador>(0);
   private Set<Solicitud> solicituds = new HashSet<Solicitud>(0);

   public Persona()
   {
   }

   public Persona(int idPersona, Ciudad ciudad, ClasePaciente clasePaciente, TipoPersona tipoPersona, String nombre, String apellidoPaterno, String apellidoMaterno, int documentoIdentidad, int telefono1, int telefono2, String sexo, String email)
   {
      this.idPersona = idPersona;
      this.ciudad = ciudad;
      this.clasePaciente = clasePaciente;
      this.tipoPersona = tipoPersona;
      this.nombre = nombre;
      this.apellidoPaterno = apellidoPaterno;
      this.apellidoMaterno = apellidoMaterno;
      this.documentoIdentidad = documentoIdentidad;
      this.telefono1 = telefono1;
      this.telefono2 = telefono2;
      this.sexo = sexo;
      this.email = email;
   }

   public Persona(int idPersona, Ciudad ciudad, ClasePaciente clasePaciente, TipoPersona tipoPersona, String nombre, String apellidoPaterno, String apellidoMaterno, int documentoIdentidad, int telefono1, int telefono2, String sexo, String email, Date fechaNacimiento, String grupoSanguineo, Date fechaReg, String usuarioReg, Date fechaMod, String usuarioMod, Date fechaBorrado, String usuarioBorrado, Set<Trabajador> trabajadors, Set<Solicitud> solicituds)
   {
      this.idPersona = idPersona;
      this.ciudad = ciudad;
      this.clasePaciente = clasePaciente;
      this.tipoPersona = tipoPersona;
      this.nombre = nombre;
      this.apellidoPaterno = apellidoPaterno;
      this.apellidoMaterno = apellidoMaterno;
      this.documentoIdentidad = documentoIdentidad;
      this.telefono1 = telefono1;
      this.telefono2 = telefono2;
      this.sexo = sexo;
      this.email = email;
      this.fechaNacimiento = fechaNacimiento;
      this.grupoSanguineo = grupoSanguineo;
      this.fechaReg = fechaReg;
      this.usuarioReg = usuarioReg;
      this.fechaMod = fechaMod;
      this.usuarioMod = usuarioMod;
      this.fechaBorrado = fechaBorrado;
      this.usuarioBorrado = usuarioBorrado;
      this.trabajadors = trabajadors;
      this.solicituds = solicituds;
   }

   @Id
   @GeneratedValue(strategy=GenerationType.IDENTITY)
   @Column(name = "id_persona", unique = true, nullable = false, insertable=false)
   public int getIdPersona()
   {
      return this.idPersona;
   }

   public void setIdPersona(int idPersona)
   {
      this.idPersona = idPersona;
   }

   @ManyToOne(fetch = FetchType.LAZY)
   @JoinColumn(name = "id_ciudad", nullable = false)
   public Ciudad getCiudad()
   {
      return this.ciudad;
   }

   public void setCiudad(Ciudad ciudad)
   {
      this.ciudad = ciudad;
   }

   @ManyToOne(fetch = FetchType.LAZY)
   @JoinColumn(name = "id_clase_paciente", nullable = false)
   public ClasePaciente getClasePaciente()
   {
      return this.clasePaciente;
   }

   public void setClasePaciente(ClasePaciente clasePaciente)
   {
      this.clasePaciente = clasePaciente;
   }

   @ManyToOne(fetch = FetchType.LAZY)
   @JoinColumn(name = "id_tipo_persona", nullable = false)
   public TipoPersona getTipoPersona()
   {
      return this.tipoPersona;
   }

   public void setTipoPersona(TipoPersona tipoPersona)
   {
      this.tipoPersona = tipoPersona;
   }

   @Column(name = "nombre", nullable = false, length = 50)
   public String getNombre()
   {
      return this.nombre;
   }

   public void setNombre(String nombre)
   {
      this.nombre = nombre;
   }

   @Column(name = "apellido_paterno", nullable = false, length = 50)
   public String getApellidoPaterno()
   {
      return this.apellidoPaterno;
   }

   public void setApellidoPaterno(String apellidoPaterno)
   {
      this.apellidoPaterno = apellidoPaterno;
   }

   @Column(name = "apellido_materno", nullable = false, length = 50)
   public String getApellidoMaterno()
   {
      return this.apellidoMaterno;
   }

   public void setApellidoMaterno(String apellidoMaterno)
   {
      this.apellidoMaterno = apellidoMaterno;
   }

   @Column(name = "documento_identidad", nullable = false)
   public int getDocumentoIdentidad()
   {
      return this.documentoIdentidad;
   }

   public void setDocumentoIdentidad(int documentoIdentidad)
   {
      this.documentoIdentidad = documentoIdentidad;
   }

   @Column(name = "telefono1", nullable = false)
   public int getTelefono1()
   {
      return this.telefono1;
   }

   public void setTelefono1(int telefono1)
   {
      this.telefono1 = telefono1;
   }

   @Column(name = "telefono2", nullable = false)
   public int getTelefono2()
   {
      return this.telefono2;
   }

   public void setTelefono2(int telefono2)
   {
      this.telefono2 = telefono2;
   }

   @Column(name = "sexo", nullable = false, length = 1)
   public String getSexo()
   {
      return this.sexo;
   }

   public void setSexo(String sexo)
   {
      this.sexo = sexo;
   }

   @Column(name = "email", nullable = false, length = 30)
   public String getEmail()
   {
      return this.email;
   }

   public void setEmail(String email)
   {
      this.email = email;
   }

   @Temporal(TemporalType.TIMESTAMP)
   @Column(name = "fecha_nacimiento", length = 29)
   public Date getFechaNacimiento()
   {
      return this.fechaNacimiento;
   }

   public void setFechaNacimiento(Date fechaNacimiento)
   {
      this.fechaNacimiento = fechaNacimiento;
   }

   @Column(name = "grupo_sanguineo", length = 5)
   public String getGrupoSanguineo()
   {
      return this.grupoSanguineo;
   }

   public void setGrupoSanguineo(String grupoSanguineo)
   {
      this.grupoSanguineo = grupoSanguineo;
   }

   @Temporal(TemporalType.TIMESTAMP)
   @Column(name = "fecha_reg", length = 29)
   public Date getFechaReg()
   {
      return this.fechaReg;
   }

   public void setFechaReg(Date fechaReg)
   {
      this.fechaReg = fechaReg;
   }

   @Column(name = "usuario_reg", length = 30)
   public String getUsuarioReg()
   {
      return this.usuarioReg;
   }

   public void setUsuarioReg(String usuarioReg)
   {
      this.usuarioReg = usuarioReg;
   }

   @Temporal(TemporalType.TIMESTAMP)
   @Column(name = "fecha_mod", length = 29)
   public Date getFechaMod()
   {
      return this.fechaMod;
   }

   public void setFechaMod(Date fechaMod)
   {
      this.fechaMod = fechaMod;
   }

   @Column(name = "usuario_mod", length = 30)
   public String getUsuarioMod()
   {
      return this.usuarioMod;
   }

   public void setUsuarioMod(String usuarioMod)
   {
      this.usuarioMod = usuarioMod;
   }

   @Temporal(TemporalType.TIMESTAMP)
   @Column(name = "fecha_borrado", length = 29)
   public Date getFechaBorrado()
   {
      return this.fechaBorrado;
   }

   public void setFechaBorrado(Date fechaBorrado)
   {
      this.fechaBorrado = fechaBorrado;
   }

   @Column(name = "usuario_borrado", length = 30)
   public String getUsuarioBorrado()
   {
      return this.usuarioBorrado;
   }

   public void setUsuarioBorrado(String usuarioBorrado)
   {
      this.usuarioBorrado = usuarioBorrado;
   }

   @OneToMany(fetch = FetchType.LAZY, mappedBy = "persona")
   public Set<Trabajador> getTrabajadors()
   {
      return this.trabajadors;
   }

   public void setTrabajadors(Set<Trabajador> trabajadors)
   {
      this.trabajadors = trabajadors;
   }

   @OneToMany(fetch = FetchType.LAZY, mappedBy = "persona")
   public Set<Solicitud> getSolicituds()
   {
      return this.solicituds;
   }

   public void setSolicituds(Set<Solicitud> solicituds)
   {
      this.solicituds = solicituds;
   }

}
