package com.sinapsistech.laboratorio.model;

// Generated Mar 2, 2015 7:12:28 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SolicitudDetalle generated by hbm2java
 */
@Entity
@Table(name = "solicitud_detalle"
      , schema = "public")
public class SolicitudDetalle implements java.io.Serializable
{

   private int idSolicitudDetalle;
   private Examen examen;
   private ListaPrecio listaPrecio;
   private Solicitud solicitud;
   private String descripcion;
   private Date fechaExamenSolicitud;
   private double precioExamen;
   private String flagEstado;
   private Date fechaReg;
   private String usuarioReg;
   private Date fechaMod;
   private String usuarioMod;
   private Date fechaBorrado;
   private String usuarioBorrado;
   private Set<RegistroResultado> registroResultados = new HashSet<RegistroResultado>(0);
   private Set<Entrega> entregas = new HashSet<Entrega>(0);
   private Set<TomaMuestra> tomaMuestras = new HashSet<TomaMuestra>(0);

   public SolicitudDetalle()
   {
   }

   public SolicitudDetalle(int idSolicitudDetalle, Examen examen, ListaPrecio listaPrecio, Solicitud solicitud, double precioExamen)
   {
      this.idSolicitudDetalle = idSolicitudDetalle;
      this.examen = examen;
      this.listaPrecio = listaPrecio;
      this.solicitud = solicitud;
      this.precioExamen = precioExamen;
   }

   public SolicitudDetalle(int idSolicitudDetalle, Examen examen, ListaPrecio listaPrecio, Solicitud solicitud, String descripcion, Date fechaExamenSolicitud, double precioExamen, String flagEstado, Date fechaReg, String usuarioReg, Date fechaMod, String usuarioMod, Date fechaBorrado, String usuarioBorrado, Set<RegistroResultado> registroResultados, Set<Entrega> entregas, Set<TomaMuestra> tomaMuestras)
   {
      this.idSolicitudDetalle = idSolicitudDetalle;
      this.examen = examen;
      this.listaPrecio = listaPrecio;
      this.solicitud = solicitud;
      this.descripcion = descripcion;
      this.fechaExamenSolicitud = fechaExamenSolicitud;
      this.precioExamen = precioExamen;
      this.flagEstado = flagEstado;
      this.fechaReg = fechaReg;
      this.usuarioReg = usuarioReg;
      this.fechaMod = fechaMod;
      this.usuarioMod = usuarioMod;
      this.fechaBorrado = fechaBorrado;
      this.usuarioBorrado = usuarioBorrado;
      this.registroResultados = registroResultados;
      this.entregas = entregas;
      this.tomaMuestras = tomaMuestras;
   }

   @Id
   @GeneratedValue(strategy=GenerationType.IDENTITY)
   @Column(name = "id_solicitud_detalle", unique = true, nullable = false, insertable=false)
   public int getIdSolicitudDetalle()
   {
      return this.idSolicitudDetalle;
   }

   public void setIdSolicitudDetalle(int idSolicitudDetalle)
   {
      this.idSolicitudDetalle = idSolicitudDetalle;
   }

   @ManyToOne(fetch = FetchType.LAZY)
   @JoinColumn(name = "id_examen", nullable = false)
   public Examen getExamen()
   {
      return this.examen;
   }

   public void setExamen(Examen examen)
   {
      this.examen = examen;
   }

   @ManyToOne(fetch = FetchType.LAZY)
   @JoinColumn(name = "id_lista_precio", nullable = false)
   public ListaPrecio getListaPrecio()
   {
      return this.listaPrecio;
   }

   public void setListaPrecio(ListaPrecio listaPrecio)
   {
      this.listaPrecio = listaPrecio;
   }

   @ManyToOne(fetch = FetchType.LAZY)
   @JoinColumn(name = "id_solicitud", nullable = false)
   public Solicitud getSolicitud()
   {
      return this.solicitud;
   }

   public void setSolicitud(Solicitud solicitud)
   {
      this.solicitud = solicitud;
   }

   @Column(name = "descripcion", length = 200)
   public String getDescripcion()
   {
      return this.descripcion;
   }

   public void setDescripcion(String descripcion)
   {
      this.descripcion = descripcion;
   }

   @Temporal(TemporalType.TIMESTAMP)
   @Column(name = "fecha_examen_solicitud", length = 29)
   public Date getFechaExamenSolicitud()
   {
      return this.fechaExamenSolicitud;
   }

   public void setFechaExamenSolicitud(Date fechaExamenSolicitud)
   {
      this.fechaExamenSolicitud = fechaExamenSolicitud;
   }

   @Column(name = "precio_examen", nullable = false, precision = 17, scale = 17)
   public double getPrecioExamen()
   {
      return this.precioExamen;
   }

   public void setPrecioExamen(double precioExamen)
   {
      this.precioExamen = precioExamen;
   }

   @Column(name = "flag_estado", length = 2)
   public String getFlagEstado()
   {
      return this.flagEstado;
   }

   public void setFlagEstado(String flagEstado)
   {
      this.flagEstado = flagEstado;
   }

   @Temporal(TemporalType.TIMESTAMP)
   @Column(name = "fecha_reg", length = 29)
   public Date getFechaReg()
   {
      return this.fechaReg;
   }

   public void setFechaReg(Date fechaReg)
   {
      this.fechaReg = fechaReg;
   }

   @Column(name = "usuario_reg", length = 30)
   public String getUsuarioReg()
   {
      return this.usuarioReg;
   }

   public void setUsuarioReg(String usuarioReg)
   {
      this.usuarioReg = usuarioReg;
   }

   @Temporal(TemporalType.TIMESTAMP)
   @Column(name = "fecha_mod", length = 29)
   public Date getFechaMod()
   {
      return this.fechaMod;
   }

   public void setFechaMod(Date fechaMod)
   {
      this.fechaMod = fechaMod;
   }

   @Column(name = "usuario_mod", length = 30)
   public String getUsuarioMod()
   {
      return this.usuarioMod;
   }

   public void setUsuarioMod(String usuarioMod)
   {
      this.usuarioMod = usuarioMod;
   }

   @Temporal(TemporalType.TIMESTAMP)
   @Column(name = "fecha_borrado", length = 29)
   public Date getFechaBorrado()
   {
      return this.fechaBorrado;
   }

   public void setFechaBorrado(Date fechaBorrado)
   {
      this.fechaBorrado = fechaBorrado;
   }

   @Column(name = "usuario_borrado", length = 30)
   public String getUsuarioBorrado()
   {
      return this.usuarioBorrado;
   }

   public void setUsuarioBorrado(String usuarioBorrado)
   {
      this.usuarioBorrado = usuarioBorrado;
   }

   @OneToMany(fetch = FetchType.LAZY, mappedBy = "solicitudDetalle")
   public Set<RegistroResultado> getRegistroResultados()
   {
      return this.registroResultados;
   }

   public void setRegistroResultados(Set<RegistroResultado> registroResultados)
   {
      this.registroResultados = registroResultados;
   }

   @OneToMany(fetch = FetchType.LAZY, mappedBy = "solicitudDetalle")
   public Set<Entrega> getEntregas()
   {
      return this.entregas;
   }

   public void setEntregas(Set<Entrega> entregas)
   {
      this.entregas = entregas;
   }

   @OneToMany(fetch = FetchType.LAZY, mappedBy = "solicitudDetalle")
   public Set<TomaMuestra> getTomaMuestras()
   {
      return this.tomaMuestras;
   }

   public void setTomaMuestras(Set<TomaMuestra> tomaMuestras)
   {
      this.tomaMuestras = tomaMuestras;
   }

}
