package com.sinapsistech.laboratorio.model;

// Generated Mar 2, 2015 7:12:28 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SubTipoExamen generated by hbm2java
 */
@Entity
@Table(name = "sub_tipo_examen"
      , schema = "public")
public class SubTipoExamen implements java.io.Serializable
{

   private int idSubTipoExamen;
   private TipoExamen tipoExamen;
   private String nombre;
   private String decripcion;
   private String flagEstado;
   private Date fechaReg;
   private String usuarioReg;
   private Date fechaMod;
   private String usuarioMod;
   private Date fechaBorrado;
   private String usuarioBorrado;
   private Set<Examen> examens = new HashSet<Examen>(0);

   public SubTipoExamen()
   {
   }

   public SubTipoExamen(int idSubTipoExamen, TipoExamen tipoExamen, String nombre, String decripcion)
   {
      this.idSubTipoExamen = idSubTipoExamen;
      this.tipoExamen = tipoExamen;
      this.nombre = nombre;
      this.decripcion = decripcion;
   }

   public SubTipoExamen(int idSubTipoExamen, TipoExamen tipoExamen, String nombre, String decripcion, String flagEstado, Date fechaReg, String usuarioReg, Date fechaMod, String usuarioMod, Date fechaBorrado, String usuarioBorrado, Set<Examen> examens)
   {
      this.idSubTipoExamen = idSubTipoExamen;
      this.tipoExamen = tipoExamen;
      this.nombre = nombre;
      this.decripcion = decripcion;
      this.flagEstado = flagEstado;
      this.fechaReg = fechaReg;
      this.usuarioReg = usuarioReg;
      this.fechaMod = fechaMod;
      this.usuarioMod = usuarioMod;
      this.fechaBorrado = fechaBorrado;
      this.usuarioBorrado = usuarioBorrado;
      this.examens = examens;
   }

   @Id
   @GeneratedValue(strategy=GenerationType.IDENTITY)
   @Column(name = "id_sub_tipo_examen", unique = true, nullable = false, insertable=false)
   public int getIdSubTipoExamen()
   {
      return this.idSubTipoExamen;
   }

   public void setIdSubTipoExamen(int idSubTipoExamen)
   {
      this.idSubTipoExamen = idSubTipoExamen;
   }

   @ManyToOne(fetch = FetchType.LAZY)
   @JoinColumn(name = "id_tipo_examen", nullable = false)
   public TipoExamen getTipoExamen()
   {
      return this.tipoExamen;
   }

   public void setTipoExamen(TipoExamen tipoExamen)
   {
      this.tipoExamen = tipoExamen;
   }

   @Column(name = "nombre", nullable = false, length = 50)
   public String getNombre()
   {
      return this.nombre;
   }

   public void setNombre(String nombre)
   {
      this.nombre = nombre;
   }

   @Column(name = "decripcion", nullable = false, length = 200)
   public String getDecripcion()
   {
      return this.decripcion;
   }

   public void setDecripcion(String decripcion)
   {
      this.decripcion = decripcion;
   }

   @Column(name = "flag_estado", length = 2)
   public String getFlagEstado()
   {
      return this.flagEstado;
   }

   public void setFlagEstado(String flagEstado)
   {
      this.flagEstado = flagEstado;
   }

   @Temporal(TemporalType.TIMESTAMP)
   @Column(name = "fecha_reg", length = 29)
   public Date getFechaReg()
   {
      return this.fechaReg;
   }

   public void setFechaReg(Date fechaReg)
   {
      this.fechaReg = fechaReg;
   }

   @Column(name = "usuario_reg", length = 30)
   public String getUsuarioReg()
   {
      return this.usuarioReg;
   }

   public void setUsuarioReg(String usuarioReg)
   {
      this.usuarioReg = usuarioReg;
   }

   @Temporal(TemporalType.TIMESTAMP)
   @Column(name = "fecha_mod", length = 29)
   public Date getFechaMod()
   {
      return this.fechaMod;
   }

   public void setFechaMod(Date fechaMod)
   {
      this.fechaMod = fechaMod;
   }

   @Column(name = "usuario_mod", length = 30)
   public String getUsuarioMod()
   {
      return this.usuarioMod;
   }

   public void setUsuarioMod(String usuarioMod)
   {
      this.usuarioMod = usuarioMod;
   }

   @Temporal(TemporalType.TIMESTAMP)
   @Column(name = "fecha_borrado", length = 29)
   public Date getFechaBorrado()
   {
      return this.fechaBorrado;
   }

   public void setFechaBorrado(Date fechaBorrado)
   {
      this.fechaBorrado = fechaBorrado;
   }

   @Column(name = "usuario_borrado", length = 30)
   public String getUsuarioBorrado()
   {
      return this.usuarioBorrado;
   }

   public void setUsuarioBorrado(String usuarioBorrado)
   {
      this.usuarioBorrado = usuarioBorrado;
   }

   @OneToMany(fetch = FetchType.LAZY, mappedBy = "subTipoExamen")
   public Set<Examen> getExamens()
   {
      return this.examens;
   }

   public void setExamens(Set<Examen> examens)
   {
      this.examens = examens;
   }

}
