package com.sinapsistech.laboratorio.model;

// Generated Mar 2, 2015 7:12:28 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TipoTarifa generated by hbm2java
 */
@Entity
@Table(name = "tipo_tarifa"
      , schema = "public")
public class TipoTarifa implements java.io.Serializable
{

   private int idTipoTarifa;
   private String nombre;
   private String decripcion;
   private Integer cuota;
   private String flagEstado;
   private Date fechaReg;
   private String usuarioReg;
   private Date fechaMod;
   private String usuarioMod;
   private Date fechaBorrado;
   private String usuarioBorrado;
   private Set<Solicitud> solicituds = new HashSet<Solicitud>(0);
   private Set<ListaPrecio> listaPrecios = new HashSet<ListaPrecio>(0);

   public TipoTarifa()
   {
   }

   public TipoTarifa(int idTipoTarifa, String nombre, String decripcion)
   {
      this.idTipoTarifa = idTipoTarifa;
      this.nombre = nombre;
      this.decripcion = decripcion;
   }

   public TipoTarifa(int idTipoTarifa, String nombre, String decripcion, Integer cuota, String flagEstado, Date fechaReg, String usuarioReg, Date fechaMod, String usuarioMod, Date fechaBorrado, String usuarioBorrado, Set<Solicitud> solicituds, Set<ListaPrecio> listaPrecios)
   {
      this.idTipoTarifa = idTipoTarifa;
      this.nombre = nombre;
      this.decripcion = decripcion;
      this.cuota = cuota;
      this.flagEstado = flagEstado;
      this.fechaReg = fechaReg;
      this.usuarioReg = usuarioReg;
      this.fechaMod = fechaMod;
      this.usuarioMod = usuarioMod;
      this.fechaBorrado = fechaBorrado;
      this.usuarioBorrado = usuarioBorrado;
      this.solicituds = solicituds;
      this.listaPrecios = listaPrecios;
   }

   @Id
   @GeneratedValue(strategy=GenerationType.IDENTITY)
   @Column(name = "id_tipo_tarifa", unique = true, nullable = false, insertable=false)
   public int getIdTipoTarifa()
   {
      return this.idTipoTarifa;
   }

   public void setIdTipoTarifa(int idTipoTarifa)
   {
      this.idTipoTarifa = idTipoTarifa;
   }

   @Column(name = "nombre", nullable = false, length = 50)
   public String getNombre()
   {
      return this.nombre;
   }

   public void setNombre(String nombre)
   {
      this.nombre = nombre;
   }

   @Column(name = "decripcion", nullable = false, length = 200)
   public String getDecripcion()
   {
      return this.decripcion;
   }

   public void setDecripcion(String decripcion)
   {
      this.decripcion = decripcion;
   }

   @Column(name = "cuota")
   public Integer getCuota()
   {
      return this.cuota;
   }

   public void setCuota(Integer cuota)
   {
      this.cuota = cuota;
   }

   @Column(name = "flag_estado", length = 2)
   public String getFlagEstado()
   {
      return this.flagEstado;
   }

   public void setFlagEstado(String flagEstado)
   {
      this.flagEstado = flagEstado;
   }

   @Temporal(TemporalType.TIMESTAMP)
   @Column(name = "fecha_reg", length = 29)
   public Date getFechaReg()
   {
      return this.fechaReg;
   }

   public void setFechaReg(Date fechaReg)
   {
      this.fechaReg = fechaReg;
   }

   @Column(name = "usuario_reg", length = 30)
   public String getUsuarioReg()
   {
      return this.usuarioReg;
   }

   public void setUsuarioReg(String usuarioReg)
   {
      this.usuarioReg = usuarioReg;
   }

   @Temporal(TemporalType.TIMESTAMP)
   @Column(name = "fecha_mod", length = 29)
   public Date getFechaMod()
   {
      return this.fechaMod;
   }

   public void setFechaMod(Date fechaMod)
   {
      this.fechaMod = fechaMod;
   }

   @Column(name = "usuario_mod", length = 30)
   public String getUsuarioMod()
   {
      return this.usuarioMod;
   }

   public void setUsuarioMod(String usuarioMod)
   {
      this.usuarioMod = usuarioMod;
   }

   @Temporal(TemporalType.TIMESTAMP)
   @Column(name = "fecha_borrado", length = 29)
   public Date getFechaBorrado()
   {
      return this.fechaBorrado;
   }

   public void setFechaBorrado(Date fechaBorrado)
   {
      this.fechaBorrado = fechaBorrado;
   }

   @Column(name = "usuario_borrado", length = 30)
   public String getUsuarioBorrado()
   {
      return this.usuarioBorrado;
   }

   public void setUsuarioBorrado(String usuarioBorrado)
   {
      this.usuarioBorrado = usuarioBorrado;
   }

   @OneToMany(fetch = FetchType.LAZY, mappedBy = "tipoTarifa")
   public Set<Solicitud> getSolicituds()
   {
      return this.solicituds;
   }

   public void setSolicituds(Set<Solicitud> solicituds)
   {
      this.solicituds = solicituds;
   }

   @OneToMany(fetch = FetchType.LAZY, mappedBy = "tipoTarifa")
   public Set<ListaPrecio> getListaPrecios()
   {
      return this.listaPrecios;
   }

   public void setListaPrecios(Set<ListaPrecio> listaPrecios)
   {
      this.listaPrecios = listaPrecios;
   }

}
