package com.sinapsistech.laboratorio.model;

// Generated Mar 2, 2015 7:12:28 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Trabajador generated by hbm2java
 */
@Entity
@Table(name = "trabajador"
      , schema = "public")
public class Trabajador implements java.io.Serializable
{

   private int idTrabajador;
   private Cargo cargo;
   private Especialidad especialidad;
   private Persona persona;
   private Date fechaIngreso;
   private Date fechaRetiro;
   private String observaciones;
   private String flagEstado;
   private Date fechaReg;
   private String usuarioReg;
   private Date fechaMod;
   private String usuarioMod;
   private Date fechaBorrado;
   private String usuarioBorrado;
   private Set<Solicitud> solicituds = new HashSet<Solicitud>(0);
   private Set<TomaMuestra> tomaMuestras = new HashSet<TomaMuestra>(0);
   private Set<Entrega> entregas = new HashSet<Entrega>(0);
   private Set<RegistroResultado> registroResultados = new HashSet<RegistroResultado>(0);

   public Trabajador()
   {
   }

   public Trabajador(int idTrabajador, Cargo cargo, Especialidad especialidad, Persona persona)
   {
      this.idTrabajador = idTrabajador;
      this.cargo = cargo;
      this.especialidad = especialidad;
      this.persona = persona;
   }

   public Trabajador(int idTrabajador, Cargo cargo, Especialidad especialidad, Persona persona, Date fechaIngreso, Date fechaRetiro, String observaciones, String flagEstado, Date fechaReg, String usuarioReg, Date fechaMod, String usuarioMod, Date fechaBorrado, String usuarioBorrado, Set<Solicitud> solicituds, Set<TomaMuestra> tomaMuestras, Set<Entrega> entregas, Set<RegistroResultado> registroResultados)
   {
      this.idTrabajador = idTrabajador;
      this.cargo = cargo;
      this.especialidad = especialidad;
      this.persona = persona;
      this.fechaIngreso = fechaIngreso;
      this.fechaRetiro = fechaRetiro;
      this.observaciones = observaciones;
      this.flagEstado = flagEstado;
      this.fechaReg = fechaReg;
      this.usuarioReg = usuarioReg;
      this.fechaMod = fechaMod;
      this.usuarioMod = usuarioMod;
      this.fechaBorrado = fechaBorrado;
      this.usuarioBorrado = usuarioBorrado;
      this.solicituds = solicituds;
      this.tomaMuestras = tomaMuestras;
      this.entregas = entregas;
      this.registroResultados = registroResultados;
   }

   @Id
   @GeneratedValue(strategy=GenerationType.IDENTITY)
   @Column(name = "id_trabajador", unique = true, nullable = false, insertable=false)
   public int getIdTrabajador()
   {
      return this.idTrabajador;
   }

   public void setIdTrabajador(int idTrabajador)
   {
      this.idTrabajador = idTrabajador;
   }

   @ManyToOne(fetch = FetchType.LAZY)
   @JoinColumn(name = "id_cargo", nullable = false)
   public Cargo getCargo()
   {
      return this.cargo;
   }

   public void setCargo(Cargo cargo)
   {
      this.cargo = cargo;
   }

   @ManyToOne(fetch = FetchType.LAZY)
   @JoinColumn(name = "id_especialidad", nullable = false)
   public Especialidad getEspecialidad()
   {
      return this.especialidad;
   }

   public void setEspecialidad(Especialidad especialidad)
   {
      this.especialidad = especialidad;
   }

   @ManyToOne(fetch = FetchType.LAZY)
   @JoinColumn(name = "id_persona", nullable = false)
   public Persona getPersona()
   {
      return this.persona;
   }

   public void setPersona(Persona persona)
   {
      this.persona = persona;
   }

   @Temporal(TemporalType.TIMESTAMP)
   @Column(name = "fecha_ingreso", length = 29)
   public Date getFechaIngreso()
   {
      return this.fechaIngreso;
   }

   public void setFechaIngreso(Date fechaIngreso)
   {
      this.fechaIngreso = fechaIngreso;
   }

   @Temporal(TemporalType.TIMESTAMP)
   @Column(name = "fecha_retiro", length = 29)
   public Date getFechaRetiro()
   {
      return this.fechaRetiro;
   }

   public void setFechaRetiro(Date fechaRetiro)
   {
      this.fechaRetiro = fechaRetiro;
   }

   @Column(name = "observaciones", length = 200)
   public String getObservaciones()
   {
      return this.observaciones;
   }

   public void setObservaciones(String observaciones)
   {
      this.observaciones = observaciones;
   }

   @Column(name = "flag_estado", length = 2)
   public String getFlagEstado()
   {
      return this.flagEstado;
   }

   public void setFlagEstado(String flagEstado)
   {
      this.flagEstado = flagEstado;
   }

   @Temporal(TemporalType.TIMESTAMP)
   @Column(name = "fecha_reg", length = 29)
   public Date getFechaReg()
   {
      return this.fechaReg;
   }

   public void setFechaReg(Date fechaReg)
   {
      this.fechaReg = fechaReg;
   }

   @Column(name = "usuario_reg", length = 30)
   public String getUsuarioReg()
   {
      return this.usuarioReg;
   }

   public void setUsuarioReg(String usuarioReg)
   {
      this.usuarioReg = usuarioReg;
   }

   @Temporal(TemporalType.TIMESTAMP)
   @Column(name = "fecha_mod", length = 29)
   public Date getFechaMod()
   {
      return this.fechaMod;
   }

   public void setFechaMod(Date fechaMod)
   {
      this.fechaMod = fechaMod;
   }

   @Column(name = "usuario_mod", length = 30)
   public String getUsuarioMod()
   {
      return this.usuarioMod;
   }

   public void setUsuarioMod(String usuarioMod)
   {
      this.usuarioMod = usuarioMod;
   }

   @Temporal(TemporalType.TIMESTAMP)
   @Column(name = "fecha_borrado", length = 29)
   public Date getFechaBorrado()
   {
      return this.fechaBorrado;
   }

   public void setFechaBorrado(Date fechaBorrado)
   {
      this.fechaBorrado = fechaBorrado;
   }

   @Column(name = "usuario_borrado", length = 30)
   public String getUsuarioBorrado()
   {
      return this.usuarioBorrado;
   }

   public void setUsuarioBorrado(String usuarioBorrado)
   {
      this.usuarioBorrado = usuarioBorrado;
   }

   @OneToMany(fetch = FetchType.LAZY, mappedBy = "trabajador")
   public Set<Solicitud> getSolicituds()
   {
      return this.solicituds;
   }

   public void setSolicituds(Set<Solicitud> solicituds)
   {
      this.solicituds = solicituds;
   }

   @OneToMany(fetch = FetchType.LAZY, mappedBy = "trabajador")
   public Set<TomaMuestra> getTomaMuestras()
   {
      return this.tomaMuestras;
   }

   public void setTomaMuestras(Set<TomaMuestra> tomaMuestras)
   {
      this.tomaMuestras = tomaMuestras;
   }

   @OneToMany(fetch = FetchType.LAZY, mappedBy = "trabajador")
   public Set<Entrega> getEntregas()
   {
      return this.entregas;
   }

   public void setEntregas(Set<Entrega> entregas)
   {
      this.entregas = entregas;
   }

   @OneToMany(fetch = FetchType.LAZY, mappedBy = "trabajador")
   public Set<RegistroResultado> getRegistroResultados()
   {
      return this.registroResultados;
   }

   public void setRegistroResultados(Set<RegistroResultado> registroResultados)
   {
      this.registroResultados = registroResultados;
   }

}
