package com.sinapsistech.laboratorio.model;

// Generated Mar 2, 2015 7:12:28 PM by Hibernate Tools 4.3.1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * UsuarioRol generated by hbm2java
 */
@Entity
@Table(name = "usuario_rol"
      , schema = "public")
public class UsuarioRol implements java.io.Serializable
{

   private int correlativo;
   private Usuario usuario;
   private String rolAsignado;
   private String flagEstado;
   private Date fechaReg;
   private String usuarioReg;

   public UsuarioRol()
   {
   }

   public UsuarioRol(int correlativo, Usuario usuario)
   {
      this.correlativo = correlativo;
      this.usuario = usuario;
   }

   public UsuarioRol(int correlativo, Usuario usuario, String rolAsignado, String flagEstado, Date fechaReg, String usuarioReg)
   {
      this.correlativo = correlativo;
      this.usuario = usuario;
      this.rolAsignado = rolAsignado;
      this.flagEstado = flagEstado;
      this.fechaReg = fechaReg;
      this.usuarioReg = usuarioReg;
   }

   @Id
   @GeneratedValue(strategy=GenerationType.IDENTITY)
   @Column(name = "correlativo", unique = true, nullable = false, insertable=false)
   public int getCorrelativo()
   {
      return this.correlativo;
   }

   public void setCorrelativo(int correlativo)
   {
      this.correlativo = correlativo;
   }

   @ManyToOne(fetch = FetchType.LAZY)
   @JoinColumn(name = "id_usuario", nullable = false)
   public Usuario getUsuario()
   {
      return this.usuario;
   }

   public void setUsuario(Usuario usuario)
   {
      this.usuario = usuario;
   }

   @Column(name = "rol_asignado", length = 10)
   public String getRolAsignado()
   {
      return this.rolAsignado;
   }

   public void setRolAsignado(String rolAsignado)
   {
      this.rolAsignado = rolAsignado;
   }

   @Column(name = "flag_estado", length = 2)
   public String getFlagEstado()
   {
      return this.flagEstado;
   }

   public void setFlagEstado(String flagEstado)
   {
      this.flagEstado = flagEstado;
   }

   @Temporal(TemporalType.TIMESTAMP)
   @Column(name = "fecha_reg", length = 29)
   public Date getFechaReg()
   {
      return this.fechaReg;
   }

   public void setFechaReg(Date fechaReg)
   {
      this.fechaReg = fechaReg;
   }

   @Column(name = "usuario_reg", length = 30)
   public String getUsuarioReg()
   {
      return this.usuarioReg;
   }

   public void setUsuarioReg(String usuarioReg)
   {
      this.usuarioReg = usuarioReg;
   }

}
